---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: home-assistant
    network_mode: host
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /run/dbus:/run/dbus:ro
      - ./appdata/config:/config
    #ports:
    #  - 8123:8123 #optional
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: always